### ISSUE TITLE
pre-retirement noise from retiring packages

### ISSUE THREAD

**Issue by rsbivand** [hypertidy/graticule#20]
I think:
[00check.log](https://github.com/hypertidy/graticule/files/11516669/00check.log)
with
[testthat.Rout.zip](https://github.com/hypertidy/graticule/files/11516671/testthat.Rout.zip)
is another response to package startup messages, like: https://github.com/Trackage/trip/issues/52

**Comment by mdsumner** [comment]
thanks Roger, updated on CRAN now
